- name: disable nodejs
  command: dnf module disable nodejs -y

- name: enable nodejs
  command: dnf module enable nodejs:20 -y

- name: install nodejs and mysql
  dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - nodejs
    - mysql

- name: add user expense
  user:
    name: expense
  
- name: app pre requisites
  import_role:
    name: common
    tasks_from: app-pre-req
  tags:
    - deployment

- name: install npm dependencies
  command: npm install
  args:
    chdir: /app
  tags:
    - deployment
  
- name: copy backend service
  template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  notify:
    - demon-reload

- name: install python dependencies
  pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import data to mysql
  community.mysql.mysql_db:
    name: load schema
    login_host: "{{ login_host }}"
    login_user: root
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    state: import

- name: start and enable backend
  service:
    name: backend
    state: started
    enabled: yes
  tags:
    - deployment
# - name: start and enable backend
#   service:
#     name: backend
#     state: restarted
    