- name: delete {{ app_location }} directory
  file:
    path: "{{ app_location }}"
    state: absent

- name: create {{ app_location }} directory
  file:
    path: "{{ app_location }}"
    state: directory

- name: unzip "{{ component }}"
  unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_location }}"
    remote_src: yes